version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

      - run:
          name: Maven Build
          command: mvn clean install

      - run:
          name: Run Tests
          command: mvn test

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

      - run:
          name: Generate Checkstyle Report
          command: mvn checkstyle:checkstyle

      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report

      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: checkstyle.html
          destination: checkstyle_reports

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
