version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  
    steps:
      - checkout  
      
      - run:
          name: Install Maven
          command: apt-get update && apt-get install -y maven
      
      - run:
          name: Run Tests
          command: mvn test  
      
      - run:
          name: Build Application
          command: mvn clean install  

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  
