version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

      - run:
          name: Maven Build
          command: mvn clean install -X

      - run:
          name: Run Tests
          command: mvn test -X

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check -X

      - run:
          name: Generate Checkstyle Report
          command: mvn checkstyle:checkstyle -X

      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report -X

      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: checkstyle.html
          destination: checkstyle_reports

      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "ci@circleci.com"
            git remote set-url origin https://$Github_token@github.com/HAZOURLIMohamedMehdi/ceri-m1-techniques-de-test.git
            git fetch origin gh-pages || git checkout --orphan gh-pages 

            mvn javadoc:javadoc

            mkdir -p docs
            cp -R target/reports/apidocs/* docs/  

            git add docs/*
            git commit -m "Update Javadoc"

            git push origin gh-pages

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
